import AppKit
import SwiftTerm

/// Panel surface that *displays* a herdr pane and forwards typing back to it.
///
/// ## Why not `LocalProcessTerminalView`
///
/// Standalone mode uses `TerminalSurface`, which owns a PTY. In herdr mode the
/// PTY belongs to herdr, so Terminal Fly must not spawn one — it only renders
/// what herdr reports and ships keystrokes back. So this subclasses the plain
/// `TerminalView` (no process) and:
///
///  * pushes screen text in with `terminal.feed(text:)`
///  * catches outgoing bytes in `send(source:data:)` and forwards them to herdr
///
/// ## Repaint strategy
///
/// herdr has no incremental-output API (see `HerdrSession`), so each poll is a
/// full screen snapshot. Feeding a full snapshot into a live terminal would
/// append rather than replace, so before feeding we reset the terminal — see
/// `show(screen:)` for why that is safe here.
final class HerdrDisplaySurface: TerminalView {
    /// Outgoing bytes from the keyboard, destined for herdr.
    ///
    /// Set by `AppCoordinator` to `session.sendText` / `sendKeys`. When nil the
    /// panel is read-only (still useful for watching a long build).
    var onInput: ((ArraySlice<UInt8>) -> Void)?

    private var lastScreen: String?

    override init(frame: CGRect) {
        super.init(frame: frame, font: nil)
        configureForDisplay()
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) is not used — the panel builds its view in code")
    }

    private func configureForDisplay() {
        // Deliberately no `terminalDelegate`: keystrokes funnel through the
        // `send(source: Terminal, data:)` override below, so conforming to the
        // full `TerminalViewDelegate` protocol would be dead weight. A side
        // benefit is that SwiftTerm's OSC 52 clipboard writes and OSC 8 link
        // opens stay inert — a viewer pane should not act on the remote pane's
        // escape sequences.
        allowMouseReporting = false
    }

    // MARK: - Rendering

    /// Replaces the visible screen with `screen` (ANSI text from `pane.read`).
    ///
    /// The reset-before-feed is deliberate. The snapshot is absolute state, not a
    /// delta, so appending it would duplicate every line on every poll. Clearing
    /// first makes each repaint idempotent, at the cost of losing the terminal's
    /// own scrollback — acceptable because herdr owns the scrollback and is the
    /// thing that would scroll it.
    func show(screen: String) {
        guard screen != lastScreen else { return }
        lastScreen = screen

        clearScreen()
        feed(text: screen)
        needsDisplay = true
    }

    private func clearScreen() {
        // Reset attributes, home the cursor, erase everything. This is the
        // standard RIS-free clear used by TUI programs.
        feed(text: "\u{1B}[0m\u{1B}[2J\u{1B}[H")
    }

    /// Writes a one-off status line (used for the disconnected state).
    func showStatus(_ message: String) {
        lastScreen = nil
        clearScreen()
        feed(text: "\u{1B}[33m\(message)\u{1B}[0m\r\n")
        needsDisplay = true
    }

    // MARK: - Input

    /// SwiftTerm routes keyboard-generated bytes here — `keyDown` and friends
    /// funnel through this single method, which is why it is the right hook.
    /// In a `LocalProcessTerminalView` this writes to the PTY; here it goes to
    /// herdr instead.
    override func send(source: Terminal, data: ArraySlice<UInt8>) {
        guard let onInput else { return }
        onInput(data)
    }

    /// The pane can change under us (user picks another pane); forcing the next
    /// `show(screen:)` to paint avoids a blank panel.
    func invalidateScreenCache() {
        lastScreen = nil
    }

    /// Reads back the rendered screen.
    ///
    /// Used by `--herdr-uitest` to assert on what is *actually displayed* rather
    /// than on what was requested. Reads the terminal buffer, so it reflects
    /// SwiftTerm's interpretation rather than the raw string we fed in.
    func screenText() -> String {
        let terminal = getTerminal()
        let end = Position(col: max(0, terminal.cols - 1), row: max(0, terminal.rows - 1))
        return terminal.getText(start: Position(col: 0, row: 0), end: end)
    }

    /// Feeds keystrokes through the same path SwiftTerm uses for real input.
    ///
    /// For `--herdr-uitest`. Synthesising real `NSEvent`s would need a focusable
    /// key window and would be flaky headlessly; routing through `send(...)` —
    /// which is exactly where `keyDown` delivers bytes — tests the wiring that
    /// actually matters.
    func simulateTyping(_ text: String) {
        send(source: getTerminal(), data: ArraySlice(Array(text.utf8)))
    }
}
